kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-control
  namespace: cybercaronte
subjects:
- kind: User
  name: cybercaronte
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: cybercaronte-full-control
  apiGroup: rbac.authorization.k8s.io