kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-control
  namespace: equipo
subjects:
- kind: Group
  name: developers
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: full-control
  apiGroup: rbac.authorization.k8s.io