kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: full-control
rules:
- apiGroups: ["extensions", "apps", ""]
  resources: ["pods", "deployments", "secrets", "services", "replicasets"]
  verbs: ["*"]